# -*- coding: utf-8 -*-
"""intro_to_tensors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fYPKwaoVZil43wlgUTTgBFpByWtkG7SO
"""



import torch

scalar=torch.tensor(7)
scalar

scalar.ndim

scalar.item()

vector=torch.tensor([7,7])

vector.shape

#matrix
MATRIX=torch.tensor([[7,8],[9,10]])

MATRIX.ndim

MATRIX.shape

TENSOR=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])



TENSOR.ndim

random_tensor=torch.rand(size=[3,244,244],dtype=torch.float16)
random_tensor

rangee=torch.arange(0,1000,100)
rangee
zeroed=torch.zeros_like(input=rangee)
zeroed

some_tensor=torch.rand(3,4,2)
some_tensor

some_tensor.size()

some_tensor.shape

some_tensor.device

tensor=torch.tensor([1,2,3])
tensor=tensor+10
tensor

tensor=torch.tensor([1,2,3])
tensor=tensor*10
tensor

tensor=torch.tensor([1,2,3])
tensor=tensor-10
tensor

tensor=torch.tensor([1,2,3])
tensor=torch.mul(tensor,20)
tensor

# ###Matrix Multiplication
# I understood

##Tensor Aggregation
x=torch.arange(1,100,5)
x

x=torch.mean(x.type(torch.float32))
y=x.type(torch.float32).mean()
x

